### ISSUE TITLE
arm5 (GOARCH=arm GOARM=5)  painc

### ISSUE THREAD

**Issue by 355911097** [fumiama/sqlite3#1]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x24 pc=0x527cd0]

goroutine 1 [running]:
github.com/fumiama/sqlite3/lib.Xsqlite3WhereBegin(0x1c70c80, 0xa69008a0, 0xa590b3b8, 0x0, 0xa590b1b8, 0xa5907548, 0xa5900000, 0x140, 0x0)
	C:/Users/go/pkg/mod/github.com/fumiama/sqlite3@v1.14.6/lib/sqlite_linux_arm.go:138142 +0xa7c
github.com/fumiama/sqlite3/lib.Xsqlite3Select(0x1c70c80, 0xa69008a0, 0xa590b138, 0xa6900ee0, 0x0)
	C:/Users/go/pkg/mod/github.com/fumiama/sqlite3@v1.14.6/lib/sqlite_linux_arm.go:122254 +0x314c
github.com/fumiama/sqlite3/lib.yy_reduce(0x1c70c80, 0xa69009d8, 0x54, 0x1, 0xa590b566, 0x0, 0xa69008a0, 0x530000)
	C:/Users/go/pkg/mod/github.com/fumiama/sqlite3@v1.14.6/lib/sqlite_linux_arm.go:144340 +0x1260
github.com/fumiama/sqlite3/lib.Xsqlite3Parser(0x1c70c80, 0xa69009d8, 0x1, 0xa590b566, 0x0)
	C:/Users/go/pkg/mod/github.com/fumiama/sqlite3@v1.14.6/lib/sqlite_linux_arm.go:145951 +0xac
github.com/fumiama/sqlite3/lib.Xsqlite3RunParser(0x1c70c80, 0xa69008a0, 0xa590b566, 0xa69009ac, 0x0)
	C:/Users/go/pkg/mod/github.com/fumiama/sqlite3@v1.14.6/lib/sqlite_linux_arm.go:147100 +0x1ac
github.com/fumiama/sqlite3/lib.sqlite3Prepare(0x1c70c80, 0xa5f00018, 0xa590b538, 0xffffffff, 0x80, 0x0, 0xa6900880, 0xa6900884, 0x0)
	C:/Users/go/pkg/mod/github.com/fumiama/sqlite3@v1.14.6/lib/sqlite_linux_arm.go:114937 +0x6d4
github.com/fumiama/sqlite3/lib.sqlite3LockAndPrepare(0x1c70c80, 0xa5f00018, 0xa590b538, 0xffffffff, 0x80, 0x0, 0xa6900880, 0xa6900884, 0x418628)
	C:/Users/go/pkg/mod/github.com/fumiama/sqlite3@v1.14.6/lib/sqlite_linux_arm.go:115030 +0x114
github.com/fumiama/sqlite3/lib.Xsqlite3_prepare_v2(...)
	C:/Users/go/pkg/mod/github.com/fumiama/sqlite3@v1.14.6/lib/sqlite_linux_arm.go:115103
github.com/fumiama/sqlite3/lib.Xsqlite3_exec(0x1c70c80, 0xa5f00018, 0xa590b538, 0x686bcc, 0xa6900848, 0x0, 0x0)
	C:/Users/go/pkg/mod/github.com/fumiama/sqlite3@v1.14.6/lib/sqlite_linux_arm.go:108732 +0x244
github.com/fumiama/sqlite3/lib.Xsqlite3InitOne(0x1c70c80, 0xa5f00018, 0x0, 0xa6900054, 0x0, 0x0)
	C:/Users/go/pkg/mod/github.com/fumiama/sqlite3@v1.14.6/lib/sqlite_linux_arm.go:114531 +0x4dc
github.com/fumiama/sqlite3/lib.Xsqlite3Init(0x1c70c80, 0xa5f00018, 0xa6900054, 0x8)
	C:/Users/go/pkg/mod/github.com/fumiama/sqlite3@v1.14.6/lib/sqlite_linux_arm.go:114622 +0x134
github.com/fumiama/sqlite3/lib.Xsqlite3ReadSchema(0x1c70c80, 0xa6900050, 0xa69007f0)
	C:/Users/go/pkg/mod/github.com/fumiama/sqlite3@v1.14.6/lib/sqlite_linux_arm.go:114650 +0x54
github.com/fumiama/sqlite3/lib.Xsqlite3LocateTable(0x1c70c80, 0xa6900050, 0x0, 0xa590b8b8, 0x0, 0x0)
	C:/Users/go/pkg/mod/github.com/fumiama/sqlite3@v1.14.6/lib/sqlite_linux_arm.go:94209 +0x468
github.com/fumiama/sqlite3/lib.Xsqlite3LocateTableItem(0x1c70c80, 0xa6900050, 0x0, 0xa590b940, 0x0)
	C:/Users/go/pkg/mod/github.com/fumiama/sqlite3@v1.14.6/lib/sqlite_linux_arm.go:94271 +0x80
github.com/fumiama/sqlite3/lib.selectExpander(0x1c70c80, 0xa6900780, 0xa590b5b8, 0x0)
	C:/Users/go/pkg/mod/github.com/fumiama/sqlite3@v1.14.6/lib/sqlite_linux_arm.go:120711 +0x308
github.com/fumiama/sqlite3/lib.Xsqlite3WalkSelect(0x1c70c80, 0xa6900780, 0xa590b5b8, 0x3f)
	C:/Users/go/pkg/mod/github.com/fumiama/sqlite3@v1.14.6/lib/sqlite_linux_arm.go:79305 +0x5c
github.com/fumiama/sqlite3/lib.sqlite3SelectExpand(0x1c70c80, 0xa6900050, 0xa590b5b8)
	C:/Users/go/pkg/mod/github.com/fumiama/sqlite3@v1.14.6/lib/sqlite_linux_arm.go:121000 +0xb8
github.com/fumiama/sqlite3/lib.Xsqlite3SelectPrep(0x1c70c80, 0xa6900050, 0xa590b5b8, 0x0)
	C:/Users/go/pkg/mod/github.com/fumiama/sqlite3@v1.14.6/lib/sqlite_linux_arm.go:121099 +0x50
github.com/fumiama/sqlite3/lib.Xsqlite3Select(0x1c70c80, 0xa6900050, 0xa590b5b8, 0xa6900690, 0x0)
	C:/Users/go/pkg/mod/github.com/fumiama/sqlite3@v1.14.6/lib/sqlite_linux_arm.go:121667 +0x1b0
github.com/fumiama/sqlite3/lib.yy_reduce(0x1c70c80, 0xa6900188, 0x54, 0x1, 0xa5d006d5, 0x0, 0xa6900050, 0x530000)
	C:/Users/go/pkg/mod/github.com/fumiama/sqlite3@v1.14.6/lib/sqlite_linux_arm.go:144340 +0x1260
github.com/fumiama/sqlite3/lib.Xsqlite3Parser(0x1c70c80, 0xa6900188, 0x1, 0xa5d006d5, 0x0)
	C:/Users/go/pkg/mod/github.com/fumiama/sqlite3@v1.14.6/lib/sqlite_linux_arm.go:145951 +0xac
github.com/fumiama/sqlite3/lib.Xsqlite3RunParser(0x1c70c80, 0xa6900050, 0xa5d006d5, 0xa690015c, 0x0)
	C:/Users/go/pkg/mod/github.com/fumiama/sqlite3@v1.14.6/lib/sqlite_linux_arm.go:147100 +0x1ac
github.com/fumiama/sqlite3/lib.sqlite3Prepare(0x1c70c80, 0xa5f00018, 0xa5d00690, 0xffffffff, 0x80, 0x0, 0xa6700030, 0xa6700038, 0x0)
	C:/Users/go/pkg/mod/github.com/fumiama/sqlite3@v1.14.6/lib/sqlite_linux_arm.go:114937 +0x6d4
github.com/fumiama/sqlite3/lib.sqlite3LockAndPrepare(0x1c70c80, 0xa5f00018, 0xa5d00690, 0xffffffff, 0x80, 0x0, 0xa6700030, 0xa6700038, 0xa49202)
	C:/Users/go/pkg/mod/github.com/fumiama/sqlite3@v1.14.6/lib/sqlite_linux_arm.go:115030 +0x114
github.com/fumiama/sqlite3/lib.Xsqlite3_prepare_v2(...)
	C:/Users/go/pkg/mod/github.com/fumiama/sqlite3@v1.14.6/lib/sqlite_linux_arm.go:115103
github.com/fumiama/sqlite3.(*conn).prepareV2(0x1d03480, 0x1d0fb70, 0x0, 0x0, 0x0)
	C:/Users/go/pkg/mod/github.com/fumiama/sqlite3@v1.14.6/sqlite.go:1182 +0x120
github.com/fumiama/sqlite3.(*stmt).query(0x1cfb980, 0x724184, 0x1c1c080, 0x1ce1f08, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
	C:/Users/go/pkg/mod/github.com/fumiama/sqlite3@v1.14.6/sqlite.go:609 +0xc8
github.com/fumiama/sqlite3.(*conn).query(0x1d03480, 0x724184, 0x1c1c080, 0x1d42000, 0x45, 0x1ce1f08, 0x1, 0x1, 0x0, 0x0, ...)
	C:/Users/go/pkg/mod/github.com/fumiama/sqlite3@v1.14.6/sqlite.go:1388 +0xe0
github.com/fumiama/sqlite3.(*conn).QueryContext(0x1d03480, 0x724184, 0x1c1c080, 0x1d42000, 0x45, 0x1ce1f08, 0x1, 0x1, 0xa6c5b078, 0x19218, ...)
	C:/Users/go/pkg/mod/github.com/fumiama/sqlite3@v1.14.6/sqlite_go18.go:38 +0x54
database/sql.ctxDriverQuery(0x724184, 0x1c1c080, 0xa6c5b090, 0x1d03480, 0x0, 0x0, 0x1d42000, 0x45, 0x1ce1f08, 0x1, ...)
	d:/go/src/database/sql/ctxutil.go:48 +0x18c
database/sql.(*DB).queryDC.func1()
	d:/go/src/database/sql/sql.go:1650 +0x160
database/sql.withLock(0x721a94, 0x1d060c0, 0x1d0fd60)
	d:/go/src/database/sql/sql.go:3294 +0x60
database/sql.(*DB).queryDC(0x1c630e0, 0x724184, 0x1c1c080, 0x0, 0x0, 0x1d060c0, 0x1cfb978, 0x1d42000, 0x45, 0x1cfb970, ...)
	d:/go/src/database/sql/sql.go:1645 +0x3f0
database/sql.(*DB).query(0x1c630e0, 0x724184, 0x1c1c080, 0x1d42000, 0x45, 0x1cfb970, 0x1, 0x1, 0x1, 0x1cfb960, ...)
	d:/go/src/database/sql/sql.go:1628 +0xdc
database/sql.(*DB).QueryContext(0x1c630e0, 0x724184, 0x1c1c080, 0x1d42000, 0x45, 0x1cfb970, 0x1, 0x1, 0x3bd138, 0xa389a0, ...)
	d:/go/src/database/sql/sql.go:1605 +0x90
gorm.io/gorm/callbacks.Query(0x1d03500)
	C:/Users/go/pkg/mod/gorm.io/gorm@v1.23.8/callbacks/query.go:18 +0xe8
gorm.io/gorm.(*processor).Execute(0x1ce71d0, 0x1d03500, 0x65159c)
	C:/Users/go/pkg/mod/gorm.io/gorm@v1.23.8/callbacks.go:130 +0x364
gorm.io/gorm.(*DB).Find(0x1d03500, 0x5dbc58, 0x1cebdf0, 0x1cebe00, 0x2, 0x2, 0x1d03500)
	C:/Users/go/pkg/mod/gorm.io/gorm@v1.23.8/finisher_api.go:170 +0x98
miniScada/models.FindChannels(0x0, 0x0, 0x15420, 0x1c1e0f0, 0x0)
	D:/GitLab/miniScada/models/t_channel.go:47 +0x158
main.main()
	D:/GitLab/miniScada/main.go:43 +0x104

**Comment by fumiama** [comment]
本仓库并非主仓库，也不负责解决问题，请前往 modernc.org 提出问题。
